name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run Go tests
      run: go test
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag git.systementor.se/noor.latif/noor-yagolangapi:$(date +%s)

    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        registry: git.systementor.se
        username: ${{ secrets.GITEA_USERNAME }}
        password: ${{ secrets.GITEA_PASSWORD }}

    - name: Push Docker image
      run: docker push git.systementor.se/noor.latif/noor-yagolangapi
